version: '3.8'

services:
  payload:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      MONGODB_URI: mongodb://mongo:27017/payload-db # Connects to the mongo service
      PAYLOAD_SECRET: 'your-payload-secret' # Change this to a strong, random secret
      NODE_ENV: development # Or 'production'
      # Add any other environment variables your app needs
      # PAYLOAD_CONFIG_PATH: src/payload.config.ts # If your config is not at the default location
    depends_on:
      - mongo
    volumes:
      - .:/app # Mounts your current directory to /app in the container for development
      - /app/node_modules # Excludes node_modules from being overwritten by the volume mount
      - /app/dist # Or /app/build, depending on your build output directory
      - /app/.payload # Persist .payload folder if needed

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: payload-db

volumes:
  mongo_data: